version: "1"
rules:
  - base: master
    upstream: google:master
    mergeMethod: rebase
    mergeUnstable: false
    assignees:
      - stuwilkins
    reviewers:
      - stuwilkins
    conflictReviewers:
      - stuwilkins

label: ":arrow_heading_down: pull"