# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install x11-xserver-utils \
                feh \
                xautolock \
                libc6 \
                libfontconfig1 \
                libpam0g \
                libx11-6 \
                libxcomposite1 \
                libxext6 \
                libxfixes3 \
                libxft2 \
                libxmuu1 \
                libxrandr2 \
                libxss1
  displayName: Install Dependencies
- script: ./autogen.sh
  displayName: 'Run autogen.sh'

- script: |
    ./configure \
      --with-pam \
      --with-pam-service-name=xsecurelock \
      --with-userfile-filename=/etc/xsecurelock/users \
      --with-banner-filename=/etc/xsecurelock/banner \
      --enable-any-user-auth \
      --enable-banner \
      --enable-wallpaper \
      --enable-no-blank \
      --with-fontconfig \
      --with-htpasswd=no \
      --with-mplayer=/usr/bin/mplayer \
      --with-mpv=/usr/bin/mpv \
      --with-pamtester=no \
      --with-xcomposite \
      --with-xf86misc=no \
      --with-xrandr \
      --with-xss \
      --with-xsync \
      --with-xfixes \
      --with-xft \
      --with-xkb
  displayName: 'Run Configure'
